import { AuditAction } from "@prisma/client";
import type { Metadata } from "next";
import { PageHeader } from "@/components/app-shell/page-header";
import { EmptyState } from "@/components/shared/empty-state";
import { Pagination } from "@/components/shared/pagination";
import { StatusBadge, fieldClass, panelClass } from "@/components/phase3/admin-ui";
import { listAuditLogs } from "@/features/audit/service";
import { auditLogListSchema } from "@/features/audit/schemas";
export const metadata: Metadata = { title: "Audit logs" };
export default async function AuditLogsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const params = await searchParams; const parsed = auditLogListSchema.safeParse({ page: params.page, pageSize: 20, action: params.action || undefined, entityType: params.entityType || undefined }); const input = parsed.success ? parsed.data : auditLogListSchema.parse({ pageSize: 20 }); const result = await listAuditLogs(input); return <><PageHeader description="Read-only history of administrative mutations and publication events." eyebrow="System" title="Audit logs" /><form className="mb-5 grid gap-3 rounded-2xl border border-border bg-surface p-4 sm:grid-cols-[1fr_1fr_auto]" method="get"><label className="grid gap-2 text-sm font-semibold">Action<select className={fieldClass} defaultValue={input.action ?? ""} name="action"><option value="">All actions</option>{Object.values(AuditAction).map((action) => <option key={action}>{action}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Entity type<input className={fieldClass} defaultValue={input.entityType} name="entityType" /></label><button className="min-h-11 self-end rounded-xl border border-border bg-surface px-4 text-sm font-semibold hover:bg-subtle">Apply filters</button></form>{result.items.length ? <div className="grid gap-3">{result.items.map((item) => <article className={panelClass} key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge status={item.action} /><strong>{item.entityType}</strong></div><p className="mt-2 text-sm text-muted">{item.actor ? `${item.actor.fullName} (${item.actor.email})` : "System actor"} · {item.createdAt.toLocaleString()}</p></div><code className="break-all text-xs text-muted">{item.entityId}</code></div>{(item.beforeSnapshot != null || item.afterSnapshot != null) && <details className="mt-4 rounded-xl bg-subtle p-3"><summary className="cursor-pointer text-sm font-semibold">View redacted change data</summary><div className="mt-3 grid gap-3 lg:grid-cols-2"><pre className="overflow-auto text-xs">{JSON.stringify(item.beforeSnapshot, null, 2) ?? "No previous value"}</pre><pre className="overflow-auto text-xs">{JSON.stringify(item.afterSnapshot, null, 2) ?? "No new value"}</pre></div></details>}</article>)}</div> : <EmptyState description="No administrative events match these filters." title="No audit entries found" />}<div className="mt-5"><Pagination page={result.pagination.page} pageCount={Math.max(1, result.pagination.totalPages)} pathname="/audit-logs" /></div></>; }
