import type { ContentBlock } from "@/features/content/schemas";
import { ActionForm, type FormAction } from "./action-form";
import { fieldClass, labelClass, panelClass } from "./admin-ui";

type System = { name: string; slug: string; shortDescription: string; longDescription?: string | null; coverMediaId?: string | null; iconMediaId?: string | null; displayOrder: number; isActive: boolean };
type Topic = { organSystemId: string; title: string; slug: string; summary?: string | null; coverMediaId?: string | null; displayOrder: number };
type Lesson = { topicId: string; title: string; slug: string; summary?: string | null; contentBlocks: ContentBlock[]; estimatedReadingMinutes: number; displayOrder: number };
type Option = { id: string; label: string };

export function OrganSystemForm({ action, item }: { action: FormAction; item?: System }) {
  return <div className={panelClass}><ActionForm action={action} label={item ? "Save organ system" : "Create organ system"}><div className="grid gap-5 sm:grid-cols-2"><label className={labelClass}>Name<input className={fieldClass} defaultValue={item?.name} name="name" required /></label><label className={labelClass}>Slug<input className={fieldClass} defaultValue={item?.slug} name="slug" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label></div><label className={labelClass}>Short description<textarea className={`${fieldClass} min-h-24 py-3`} defaultValue={item?.shortDescription} name="shortDescription" required /></label><label className={labelClass}>Long description<textarea className={`${fieldClass} min-h-36 py-3`} defaultValue={item?.longDescription ?? ""} name="longDescription" /></label><div className="grid gap-5 sm:grid-cols-3"><label className={labelClass}>Cover media ID<input className={fieldClass} defaultValue={item?.coverMediaId ?? ""} name="coverMediaId" /></label><label className={labelClass}>Icon media ID<input className={fieldClass} defaultValue={item?.iconMediaId ?? ""} name="iconMediaId" /></label><label className={labelClass}>Display order<input className={fieldClass} defaultValue={item?.displayOrder ?? 0} min="0" name="displayOrder" required type="number" /></label></div><label className="flex items-center gap-3 text-sm font-semibold text-body"><input defaultChecked={item?.isActive ?? true} name="isActive" type="checkbox" />Active and selectable when published</label></ActionForm></div>;
}

export function TopicForm({ action, item, systems }: { action: FormAction; item?: Topic; systems: Option[] }) {
  return <div className={panelClass}><ActionForm action={action} label={item ? "Save topic" : "Create topic"}><label className={labelClass}>Organ system<select className={fieldClass} defaultValue={item?.organSystemId} name="organSystemId" required><option value="">Select an organ system</option>{systems.map((system) => <option key={system.id} value={system.id}>{system.label}</option>)}</select></label><div className="grid gap-5 sm:grid-cols-2"><label className={labelClass}>Title<input className={fieldClass} defaultValue={item?.title} name="title" required /></label><label className={labelClass}>Slug<input className={fieldClass} defaultValue={item?.slug} name="slug" required /></label></div><label className={labelClass}>Summary<textarea className={`${fieldClass} min-h-28 py-3`} defaultValue={item?.summary ?? ""} name="summary" /></label><div className="grid gap-5 sm:grid-cols-2"><label className={labelClass}>Cover media ID<input className={fieldClass} defaultValue={item?.coverMediaId ?? ""} name="coverMediaId" /></label><label className={labelClass}>Display order<input className={fieldClass} defaultValue={item?.displayOrder ?? 0} min="0" name="displayOrder" required type="number" /></label></div></ActionForm></div>;
}

export function LessonForm({ action, item, topics }: { action: FormAction; item?: Lesson; topics: Option[] }) {
  const example = item?.contentBlocks ?? [{ type: "heading", level: 2, text: "Overview" }, { type: "paragraph", text: "Add lesson text here." }];
  return <div className={panelClass}><ActionForm action={action} label={item ? "Save draft changes" : "Create lesson"}><label className={labelClass}>Topic<select className={fieldClass} defaultValue={item?.topicId} name="topicId" required><option value="">Select a topic</option>{topics.map((topic) => <option key={topic.id} value={topic.id}>{topic.label}</option>)}</select></label><div className="grid gap-5 sm:grid-cols-2"><label className={labelClass}>Title<input className={fieldClass} defaultValue={item?.title} name="title" required /></label><label className={labelClass}>Slug<input className={fieldClass} defaultValue={item?.slug} name="slug" required /></label></div><label className={labelClass}>Summary<textarea className={`${fieldClass} min-h-24 py-3`} defaultValue={item?.summary ?? ""} name="summary" /></label><label className={labelClass}>Structured lesson blocks<textarea aria-describedby="blocks-help" className={`${fieldClass} min-h-80 py-3 font-mono text-xs leading-5`} defaultValue={JSON.stringify(example, null, 2)} name="contentBlocks" required /><span className="font-normal text-muted" id="blocks-help">JSON blocks are schema-validated. Supported types: heading, paragraph, image, callout, bulletList, numberedList, divider. Raw HTML is not accepted.</span></label><div className="grid gap-5 sm:grid-cols-2"><label className={labelClass}>Reading time (minutes)<input className={fieldClass} defaultValue={item?.estimatedReadingMinutes ?? 0} max="600" min="0" name="estimatedReadingMinutes" required type="number" /></label><label className={labelClass}>Display order<input className={fieldClass} defaultValue={item?.displayOrder ?? 0} min="0" name="displayOrder" required type="number" /></label></div></ActionForm></div>;
}
