import Link from "next/link";

import { BulkActionForm } from "@/components/admin/bulk-action-form";
import { formatDateTime } from "@/components/assessments/format";
import { InlineAction, type ActionState, type FormAction } from "@/components/phase3/action-form";
import { Phase6StatusBadge } from "./status-badge";
import { PersonAvatar } from "@/components/shared/person-avatar";

export type FeedbackListItem = {
  id: string; subject: string; message: string; type: string; status: string; rating: number | null; createdAt: Date;
  submitter: { fullName: string; email: string; avatarUrl: string | null } | null;
};
const typeLabel = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, (letter) => letter.toUpperCase());
type TrashAction = (id: string, state: ActionState, data?: FormData) => Promise<ActionState>;

function RowActions({ item, trashAction }: { item: FeedbackListItem; trashAction: TrashAction }) {
  return <InlineAction action={trashAction.bind(null, item.id)} ariaLabel={`Delete ${item.subject}`} confirmLabel="Move to Trash" confirmMessage="This feedback will be hidden and can be restored from Settings > Trash for 30 days." confirmTitle="Move feedback to Trash?" destructive>Delete</InlineAction>;
}

export function FeedbackList({ bulkTrashAction, items, trashAction }: { bulkTrashAction: FormAction; items: FeedbackListItem[]; trashAction: TrashAction }) {
  return <BulkActionForm action={bulkTrashAction} itemIds={items.map((item) => item.id)} itemLabel="feedback item" trashOnly>
    <div className="hidden overflow-x-auto rounded-2xl border border-border bg-surface shadow-sm md:block"><table className="w-full border-collapse text-left text-sm"><caption className="sr-only">Submitted feedback</caption><thead className="bg-subtle text-muted"><tr><th className="w-12 px-3 py-3" scope="col"><span className="sr-only">Selection</span></th><th className="px-4 py-3 font-semibold" scope="col">Feedback</th><th className="px-4 py-3 font-semibold" scope="col">User</th><th className="px-4 py-3 font-semibold" scope="col">Rating</th><th className="px-4 py-3 font-semibold" scope="col">Type</th><th className="px-4 py-3 font-semibold" scope="col">Status</th><th className="px-4 py-3 font-semibold" scope="col">Submitted</th><th className="px-4 py-3 text-right font-semibold" scope="col">Actions</th></tr></thead><tbody>{items.map((item) => <tr className="border-t border-border" key={item.id}><td className="px-3 py-4"><label className="inline-flex size-10 items-center justify-center"><span className="sr-only">Select {item.subject}</span><input className="size-4" name="ids" type="checkbox" value={item.id} /></label></td><th className="max-w-md px-4 py-4 font-normal" scope="row"><Link className="font-bold text-foreground hover:text-primary" href={`/feedback/${item.id}`}>{item.subject}</Link><p className="mt-1 line-clamp-2 text-muted">{item.message}</p></th><td className="px-4 py-4 text-body">{item.submitter ? <div className="flex items-center gap-2"><PersonAvatar name={item.submitter.fullName} size="sm" url={item.submitter.avatarUrl} /><div><p className="font-semibold">{item.submitter.fullName}</p><p className="break-all text-muted">{item.submitter.email}</p></div></div> : "Unknown user"}</td><td className="px-4 py-4 tabular-nums text-body">{item.rating ?? "Unknown"}</td><td className="px-4 py-4 text-body">{typeLabel(item.type)}</td><td className="px-4 py-4"><Phase6StatusBadge status={item.status} /></td><td className="px-4 py-4 tabular-nums text-body">{formatDateTime(item.createdAt)}</td><td className="px-4 py-4"><div className="flex justify-end"><RowActions item={item} trashAction={trashAction} /></div></td></tr>)}</tbody></table></div>
    <div className="grid gap-3 md:hidden">{items.map((item) => <article className="rounded-2xl border border-border bg-surface p-4 shadow-sm" key={item.id}><div className="flex items-start gap-3"><label className="inline-flex size-10 shrink-0 items-center justify-center"><span className="sr-only">Select {item.subject}</span><input className="size-4" name="ids" type="checkbox" value={item.id} /></label><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><Link className="font-bold text-foreground" href={`/feedback/${item.id}`}>{item.subject}</Link><Phase6StatusBadge status={item.status} /></div><p className="mt-2 line-clamp-3 text-sm leading-6 text-muted">{item.message}</p><dl className="mt-4 grid gap-2 border-t border-border pt-3 text-sm"><div className="flex items-center justify-between gap-3"><dt className="font-semibold text-muted">User</dt><dd className="flex items-center gap-2 text-right text-body">{item.submitter && <PersonAvatar name={item.submitter.fullName} size="sm" url={item.submitter.avatarUrl} />}{item.submitter?.fullName ?? "Unknown user"}</dd></div><div className="flex justify-between gap-3"><dt className="font-semibold text-muted">Rating</dt><dd className="tabular-nums text-body">{item.rating ?? "Unknown"}</dd></div><div className="flex justify-between gap-3"><dt className="font-semibold text-muted">Type</dt><dd className="text-body">{typeLabel(item.type)}</dd></div><div className="flex justify-between gap-3"><dt className="font-semibold text-muted">Submitted</dt><dd className="text-right text-body">{formatDateTime(item.createdAt)}</dd></div></dl><div className="mt-4 flex justify-end border-t border-border pt-3"><RowActions item={item} trashAction={trashAction} /></div></div></div></article>)}</div>
  </BulkActionForm>;
}
