import type { Metadata } from "next";
import { PageHeader } from "@/components/app-shell/page-header";
import { EmptyState } from "@/components/shared/empty-state";
import { Pagination } from "@/components/shared/pagination";
import { FilterBar, ResourceCard, ResourceCards, StatusBadge, fieldClass } from "@/components/phase3/admin-ui";
import { listAdmin } from "@/components/phase3/data";
import { listQuerySchema } from "@/features/content/schemas";
import { AdminMediaThumbnail } from "@/components/media/admin-media-thumbnail";
import { getAdminMediaMap } from "@/features/media/service";
export const metadata: Metadata = { title: "Topics" };
export default async function TopicsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const params = await searchParams; const systems = await listAdmin("organSystem", { page: 1, pageSize: 100, sortBy: "name", sortOrder: "asc" }); const parsed = listQuerySchema.safeParse({ page: params.page, pageSize: 15, q: params.q || undefined, status: params.status || undefined, organSystemId: params.organSystemId || undefined, sortBy: "updatedAt", sortOrder: "desc" }); const input = parsed.success ? parsed.data : listQuerySchema.parse({ pageSize: 15, sortBy: "updatedAt", sortOrder: "desc" }); const result = await listAdmin("topic", input); const media = await getAdminMediaMap(result.items.flatMap((item) => item.coverMediaId ? [item.coverMediaId] : [])); return <><PageHeader description="Search and review topics across every organ system." eyebrow="Learning content" title="Topics" /><FilterBar defaultValue={input.q}><select aria-label="Organ system" className={fieldClass} defaultValue={input.organSystemId ?? ""} name="organSystemId"><option value="">All organ systems</option>{systems.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></FilterBar>{result.items.length ? <><ResourceCards>{result.items.map((item) => <ResourceCard actions={<StatusBadge status={item.status} />} href={`/topics/${item.id}`} key={item.id} title={item.title}><AdminMediaThumbnail attached={Boolean(item.coverMediaId)} label="Cover" legacyUrl={item.coverImageUrl} media={item.coverMediaId ? media.get(item.coverMediaId) : undefined} /><p className="mt-3">{item.summary || "No summary yet."}</p></ResourceCard>)}</ResourceCards><div className="mt-5"><Pagination page={result.pagination.page} pageCount={Math.max(1, result.pagination.totalPages)} pathname="/topics" /></div></> : <EmptyState description="No topics match the current search and filters." title="No topics found" />}</>; }
