import Link from "next/link";

import { BulkActionForm } from "@/components/admin/bulk-action-form";
import { formatDateTime } from "@/components/assessments/format";
import { InlineAction, type ActionState, type FormAction } from "@/components/phase3/action-form";
import { StatusBadge } from "@/components/phase3/admin-ui";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export type QuestionListItem = {
  id: string; topicId: string; topicTitle: string | null; assessmentType: "QUIZ" | "TEST"; questionText: string; imageUrl: string | null; mediaId: string | null; explanation: string; difficulty: "EASY" | "MEDIUM" | "HARD"; conceptTag: string | null; status: "DRAFT" | "PUBLISHED" | "ARCHIVED"; isActive: boolean; createdAt: Date; updatedAt: Date; options: Array<{ id: string; key: string; label: string; displayOrder: number; optionText: string; imageUrl: string | null; mediaId: string | null; isCorrect: boolean }>;
};
type TrashAction = (id: string, state: ActionState, data: FormData) => Promise<ActionState>;

function FullQuestion({ value }: { value: string }) {
  return <span className="block max-w-72" title={value}><span aria-hidden="true" className="block truncate">{value}</span><span className="sr-only">{value}</span></span>;
}

function RowActions({ item, trashAction }: { item: QuestionListItem; trashAction: TrashAction }) {
  return <div className="flex flex-wrap justify-end gap-2"><Link aria-label={`Edit ${item.questionText}`} className={buttonVariants({ size: "sm", variant: "outline" })} href={`/questions/${item.id}`}>Edit</Link><InlineAction action={trashAction.bind(null, item.id)} ariaLabel={`Delete ${item.questionText}`} confirmLabel="Move to Trash" confirmMessage="This question will be hidden and can be restored from Settings > Trash for 30 days." confirmTitle="Move question to Trash?" destructive>Delete</InlineAction></div>;
}

export function QuestionList({ assessmentType, bulkAction, items, page, pageSize, trashAction }: { assessmentType: "QUIZ" | "TEST"; bulkAction: FormAction; items: QuestionListItem[]; page: number; pageSize: number; trashAction: TrashAction }) {
  const quiz = assessmentType === "QUIZ";
  return <BulkActionForm action={bulkAction} itemIds={items.map((item) => item.id)} itemLabel="question">
    <div className={cn("hidden overflow-x-auto rounded-2xl border bg-surface shadow-sm md:block", quiz ? "border-quiz/20" : "border-test/20")}><table aria-label={`${quiz ? "Quiz" : "Test"} questions`} className="w-full border-collapse text-left text-sm"><thead className="bg-subtle text-muted"><tr><th className="w-12 px-3 py-3" scope="col"><span className="sr-only">Selection</span></th><th className="px-3 py-3 font-semibold" scope="col">S.No</th><th className="px-3 py-3 font-semibold" scope="col">Question</th><th className="px-3 py-3 font-semibold" scope="col">Topic</th><th className="px-3 py-3 font-semibold" scope="col">Status</th><th className="px-3 py-3 font-semibold" scope="col">Activity</th><th className="px-3 py-3 font-semibold" scope="col">Difficulty</th><th className="px-3 py-3 font-semibold" scope="col">Options</th><th className="px-3 py-3 font-semibold" scope="col">Updated</th><th className="px-3 py-3 text-right font-semibold" scope="col">Actions</th></tr></thead><tbody>{items.map((item, index) => <tr className="border-t border-border" key={item.id}><td className="px-3 py-4"><label className="inline-flex size-10 items-center justify-center"><span className="sr-only">Select {item.questionText}</span><input className="size-4" name="ids" type="checkbox" value={item.id} /></label></td><td aria-label={String((page - 1) * pageSize + index + 1)} className="px-3 py-4 tabular-nums">{(page - 1) * pageSize + index + 1}</td><th className="max-w-72 px-3 py-4 font-semibold" scope="row"><FullQuestion value={item.questionText} /></th><td className="px-3 py-4">{item.topicTitle ?? "Unavailable"}</td><td className="px-3 py-4"><StatusBadge status={item.status} /></td><td className="px-3 py-4"><StatusBadge status={item.isActive ? "ACTIVE" : "INACTIVE"} /></td><td className="px-3 py-4 capitalize">{item.difficulty.toLowerCase()}</td><td className="px-3 py-4">{item.options.length} options</td><td className="whitespace-nowrap px-3 py-4 tabular-nums">{formatDateTime(item.updatedAt)}</td><td className="px-3 py-4"><RowActions item={item} trashAction={trashAction} /></td></tr>)}</tbody></table></div>
    <div className="grid gap-3 md:hidden">{items.map((item, index) => <article className={cn("rounded-2xl border bg-surface p-4 shadow-sm", quiz ? "border-quiz/20" : "border-test/20")} key={item.id}><div className="flex items-start gap-3"><label className="inline-flex size-10 shrink-0 items-center justify-center"><span className="sr-only">Select {item.questionText}</span><input className="size-4" name="ids" type="checkbox" value={item.id} /></label><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-xs font-semibold tabular-nums text-muted">S.No {(page - 1) * pageSize + index + 1}</p><div className="flex flex-wrap gap-2"><StatusBadge status={item.status} /><StatusBadge status={item.isActive ? "ACTIVE" : "INACTIVE"} /></div></div><div className="mt-2 font-semibold"><FullQuestion value={item.questionText} /></div><dl className="mt-4 grid grid-cols-2 gap-3 border-t border-border pt-3 text-sm"><div><dt className="font-semibold text-muted">Topic</dt><dd className="mt-1">{item.topicTitle ?? "Unavailable"}</dd></div><div><dt className="font-semibold text-muted">Difficulty</dt><dd className="mt-1 capitalize">{item.difficulty.toLowerCase()}</dd></div><div><dt className="font-semibold text-muted">Options</dt><dd className="mt-1">{item.options.length} options</dd></div><div><dt className="font-semibold text-muted">Updated</dt><dd className="mt-1 tabular-nums">{formatDateTime(item.updatedAt)}</dd></div></dl><div className="mt-4 border-t border-border pt-3"><RowActions item={item} trashAction={trashAction} /></div></div></div></article>)}</div>
  </BulkActionForm>;
}
